"""Brand-asset content validation — the stored MIME must describe the BYTES.

`_copy_brand_asset` validated only that the file was non-empty. The extension
came verbatim from the inbound path and the MIME was GUESSED from that
extension, then stored as truth. Downstream that stored value is authoritative:
`render.py:2298` reads `asset.mime_type`, checks only `startswith("image/")`,
and base64s the bytes into the vision call under it. So a PDF or a video named
`.jpg` reached an image/jpeg vision request.

This is item (d) of the brand-asset design and is deliberately narrow: it makes
the stored MIME honest about the content. It does NOT fix the receipt-misfile
defect, which is a routing question and needs the separate (b)+(c) piece.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
import sys

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src" / "platform"))

from agents.flyer import onboarding  # noqa: E402
from agents.flyer.onboarding import store_brand_asset  # noqa: E402
from schemas import FlyerCustomerStore  # noqa: E402

NOW = datetime(2026, 8, 14, 12, 0, tzinfo=timezone.utc)
CHAT = "15550100003@s.whatsapp.net"
PHONE = "+15550100003"

# Smallest byte strings that are unambiguously each format. Magic bytes are the
# whole point of the fix, so the fixtures are written as literal bytes rather
# than generated by a library that might normalize them.
JPEG_BYTES = bytes.fromhex("ffd8ff") + b"\xe0\x00\x10JFIF" + b"\x00" * 32
PNG_BYTES = bytes.fromhex("89504e470d0a1a0a") + b"\x00" * 32
WEBP_BYTES = b"RIFF" + (64).to_bytes(4, "little") + b"WEBPVP8 " + b"\x00" * 32
PDF_BYTES = b"%PDF-1.7\n" + b"\x00" * 64
GIF_BYTES = b"GIF89a" + b"\x00" * 32
MP4_BYTES = b"\x00\x00\x00\x18ftypmp42" + b"\x00" * 32


def _customer_state(state_path: Path) -> None:
    store = FlyerCustomerStore()
    store.customers.append(store.new_customer(
        business_name="Triveni",
        business_address="300 S Polk St",
        public_phone=PHONE,
        business_whatsapp_number=PHONE,
        authorized_request_number="+19045550104",
        business_category="restaurant",
        preferred_language="en",
        plan_id="starter",
        now=NOW,
    ).model_copy(update={"status": "active"}))
    state_path.write_text(store.model_dump_json(indent=2), encoding="utf-8")


@pytest.fixture(autouse=True)
def _flyer_state_root(tmp_path, monkeypatch):
    """FlyerBrandAsset.path is validated against FLYER_STATE_ROOT; point it at
    the sandbox so these cells write to a real disk instead of mocking the
    write they are about."""
    monkeypatch.setenv("FLYER_STATE_ROOT", str(tmp_path))


def _store(tmp_path: Path, data: bytes, name: str):
    """Drive the REAL entry point against a REAL file on disk."""
    state_path = tmp_path / "customers.json"
    _customer_state(state_path)
    media = tmp_path / name
    media.write_bytes(data)
    return store_brand_asset(
        state_path=state_path,
        chat_id=CHAT,
        sender_phone=PHONE,
        message_id="m-asset",
        media_path=media,
        text="logo",
        now=NOW,
    ), state_path


def _saved_assets(state_path: Path):
    store = FlyerCustomerStore.model_validate_json(state_path.read_text(encoding="utf-8"))
    return [a for c in store.customers for a in c.brand_assets]


# ── refusals ────────────────────────────────────────────────────────────────

@pytest.mark.parametrize("data,name,label", [
    (PDF_BYTES, "logo.jpg", "a PDF wearing a .jpg name"),
    (MP4_BYTES, "logo.jpg", "a video wearing a .jpg name"),
    (GIF_BYTES, "logo.png", "a GIF, which nothing downstream consumes"),
    (b"just some text", "logo.png", "arbitrary bytes"),
])
def test_content_that_is_not_a_supported_image_is_refused(tmp_path, data, name, label):
    """The load-bearing cell: extension says image, bytes say otherwise. Before
    this validation the file was stored and its MIME recorded as image/jpeg."""
    with pytest.raises(ValueError):
        _store(tmp_path, data, name)


def test_zero_byte_media_is_still_refused(tmp_path):
    with pytest.raises(ValueError):
        _store(tmp_path, b"", "logo.jpg")


def test_oversized_media_is_refused(tmp_path):
    oversized = JPEG_BYTES + b"\x00" * (onboarding.MAX_BRAND_ASSET_BYTES + 1)
    with pytest.raises(ValueError):
        _store(tmp_path, oversized, "logo.jpg")


def test_a_file_right_at_the_cap_is_accepted(tmp_path):
    """Boundary: the cap rejects ABOVE it, not AT it."""
    at_cap = JPEG_BYTES + b"\x00" * (onboarding.MAX_BRAND_ASSET_BYTES - len(JPEG_BYTES))
    assert len(at_cap) == onboarding.MAX_BRAND_ASSET_BYTES
    result, state_path = _store(tmp_path, at_cap, "logo.jpg")
    assert result.next_status == "brand_asset_saved"
    assert _saved_assets(state_path)[-1].mime_type == "image/jpeg"


def test_a_refused_asset_leaves_nothing_behind(tmp_path):
    """The refusal happens BEFORE the write, so no partial file and no store
    row survive it — a rejected upload must not occupy an asset id either."""
    state_path = tmp_path / "customers.json"
    _customer_state(state_path)
    before = FlyerCustomerStore.model_validate_json(state_path.read_text(encoding="utf-8"))
    media = tmp_path / "logo.jpg"
    media.write_bytes(PDF_BYTES)

    with pytest.raises(ValueError):
        store_brand_asset(
            state_path=state_path, chat_id=CHAT, sender_phone=PHONE,
            message_id="m-bad", media_path=media, text="logo", now=NOW,
        )

    after = FlyerCustomerStore.model_validate_json(state_path.read_text(encoding="utf-8"))
    assert _saved_assets(state_path) == []
    assert after.next_brand_asset_sequence == before.next_brand_asset_sequence
    assert not (state_path.parent / "brand_assets").exists() or not list(
        (state_path.parent / "brand_assets").rglob("*"))


# ── acceptances, with the MIME derived from content ─────────────────────────

@pytest.mark.parametrize("data,name,expected_mime", [
    (JPEG_BYTES, "logo.jpg", "image/jpeg"),
    (JPEG_BYTES, "logo.jpeg", "image/jpeg"),
    (PNG_BYTES, "logo.png", "image/png"),
    (WEBP_BYTES, "logo.webp", "image/webp"),
])
def test_genuine_images_are_accepted_with_their_own_mime(tmp_path, data, name, expected_mime):
    result, state_path = _store(tmp_path, data, name)
    assert result.next_status == "brand_asset_saved"
    assets = _saved_assets(state_path)
    assert len(assets) == 1
    assert assets[0].mime_type == expected_mime
    assert Path(assets[0].path).exists()


@pytest.mark.parametrize("data,name,expected_mime", [
    (PNG_BYTES, "logo.jpg", "image/png"),
    (JPEG_BYTES, "logo.png", "image/jpeg"),
    (PNG_BYTES, "logo", "image/png"),
    (JPEG_BYTES, "logo.bin", "image/jpeg"),
])
def test_a_mislabelled_but_genuine_image_is_stored_under_its_real_mime(
        tmp_path, data, name, expected_mime):
    """A phone that names a PNG `.jpg` is a mislabel, not an attack. Accept the
    file — and record what it actually IS, because that value is what the vision
    call is told downstream."""
    result, state_path = _store(tmp_path, data, name)
    assert result.next_status == "brand_asset_saved"
    assert _saved_assets(state_path)[0].mime_type == expected_mime


def test_the_stored_extension_matches_the_stored_mime(tmp_path):
    """The path and the MIME must not disagree either — a PNG saved as .jpg on
    disk is the same latent trap one layer down."""
    _result, state_path = _store(tmp_path, PNG_BYTES, "logo.jpg")
    asset = _saved_assets(state_path)[0]
    assert asset.mime_type == "image/png"
    assert Path(asset.path).suffix == ".png"


def test_stored_bytes_are_unmodified(tmp_path):
    """Validation inspects; it must not transcode."""
    _result, state_path = _store(tmp_path, PNG_BYTES, "logo.png")
    asset = _saved_assets(state_path)[0]
    assert Path(asset.path).read_bytes() == PNG_BYTES
