"""PR-A + PR-B2 — F7 catering reachability: DETERMINISTIC proposal generation +
fresh-vs-stale discriminator (unit-level).

Exercises `_try_f7_primary_intercept`'s Branch-B decision table in isolation with the
intercept's dependencies monkeypatched, so every branch is deterministic and network-free.
The classifiers (classify_catering / is_proposal_request_escape / is_amendment_phrased /
is_mix_and_match_request) and the discriminator helpers run REAL, so the pins reflect
production classification of the verbatim L0017 13:59 incident. Windows-runnable via the
fcntl stub.

PR-B2 (2026-07-21) reverses PR-A's move of active-lead proposal GENERATION onto the Hermes
creative path (no live evidence it worked): a PLAIN proposal request is now GENERATED by
cf-router via create-catering-proposal-options --auto-generate-from-menu (LLM bypassed), while
a MIX-AND-MATCH recompose still escapes to the Hermes dispatcher (--recompose-from-sent).

Reviewer proof obligations covered: the exact-incident replay opens a NEW lead over the stale
one, sends the cross-reference ack, GENERATES proposals deterministically against the new lead,
and is NEVER `f7_primary_followup_suppressed` · a plain proposal request generates against the
active lead with NO new lead · a mix-and-match request escapes to Hermes (recompose) and does
NOT auto-generate · the R2A canary amendment keeps the unchanged capture path · an inquiry-shaped
follow-up with matching identity clarifies once (no lead, no capture) · a date-only or
headcount-only contradiction opens a new lead each · idempotency (same message id twice ⇒ one
lead) · the new reason literals are declared enum members.
"""
from __future__ import annotations

import importlib.machinery
import importlib.util
import sys
from pathlib import Path
from types import SimpleNamespace

from fixtures_fleet import ensure_fcntl_stub

ensure_fcntl_stub()

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "src"
PLUGIN_DIR = SRC / "plugins" / "cf-router"
for _p in (SRC, SRC / "platform"):
    if str(_p) not in sys.path:
        sys.path.insert(0, str(_p))

PHONE = "+15550100001"
CHAT = "15550100001@lid"

# The verbatim 5th-reproduction production message (routing-validation / L0017 13:59).
INCIDENT = (
    "Hello I have a wedding coming up for 120 guests on August 8th, out of 120 "
    "guests 90 are non-vegetarian and 30 vegetarian. Provide me two best sample "
    "menus of yours , so that I can decide."
)


def _load_plugin():
    pkg = "cf_router_pra_pkg"
    for m in list(sys.modules):
        if m == pkg or m.startswith(pkg + "."):
            del sys.modules[m]
    spec = importlib.machinery.ModuleSpec(pkg, loader=None, is_package=True)
    spec.submodule_search_locations = [str(PLUGIN_DIR)]
    sys.modules[pkg] = importlib.util.module_from_spec(spec)

    def _load(name):
        full = f"{pkg}.{name}"
        loader = importlib.machinery.SourceFileLoader(full, str(PLUGIN_DIR / f"{name}.py"))
        sp = importlib.util.spec_from_loader(full, loader)
        mod = importlib.util.module_from_spec(sp)
        sys.modules[full] = mod
        loader.exec_module(mod)
        return mod

    actions_mod = _load("actions")
    hooks_mod = _load("hooks")
    return hooks_mod, actions_mod


def _event(message_id="wamid.INCIDENT"):
    return SimpleNamespace(message_id=message_id, chat_id=CHAT, timestamp="1721480400",
                           transport="whatsapp")


def _stale_lead(lead_id="L0017", event_date="2026-07-04", headcount=60,
                status="AWAITING_OWNER_APPROVAL"):
    return {
        "lead_id": lead_id, "status": status, "owner_approval_code": "#GEMAZ",
        "customer_phone": PHONE, "created_at": "2026-06-09T00:00:00+00:00",
        "updated_at": "2026-06-09T00:00:00+00:00",
        "extracted": {"event_date": event_date, "headcount": headcount},
    }


class _Spies:
    def __init__(self):
        self.audits = []
        self.creates = []
        self.clarify = []
        self.canonical = []
        self.captures = []
        self.proposals = []  # (lead_id, chat_id, message_id, text) per deterministic invoke
        self.selects = []    # (lead_id, chat_id, message_id, text) per selection invoke


def _wire(monkeypatch, hooks_mod, actions_mod, *, active_lead, role="customer",
          create_returns=None, capture_ok=True, selectable_set=None, select_rc=0):
    """Monkeypatch every dependency `_try_f7_primary_intercept` touches; the REAL
    classifiers + discriminator run. Returns a _Spies recorder.

    `selectable_set` (turn-arbitration 2026-07-26): the dict returned by
    find_selectable_proposal_set — None (default) means no SENT set exists for the lead,
    so the compound-intent selection branch is dormant."""
    from catering_amendments import CaptureResult
    s = _Spies()
    hooks_mod.F7_PROPOSAL_BRANCH_ENABLED = True
    hooks_mod.F7_PRIMARY_FOLLOWUP_REPLY = True

    monkeypatch.setattr(actions_mod, "lid_to_phone_via_identify_sender", lambda cid: (PHONE, role))
    monkeypatch.setattr(actions_mod, "find_active_catering_lead_by_sender", lambda p, c: active_lead)
    monkeypatch.setattr(actions_mod, "audit_intercepted", lambda **kw: s.audits.append(kw))

    def _create(**kw):
        s.creates.append(kw)
        if callable(create_returns):
            return create_returns(kw)
        return (True, '{"lead_id":"L0099"}')
    monkeypatch.setattr(actions_mod, "trigger_create_catering_lead", _create)
    # Deterministic generator (PR-B2): spy the subprocess invoke; rc=0 ⇒ handled ⇒ skip.
    monkeypatch.setattr(actions_mod, "invoke_create_catering_proposals",
                        lambda lead, cid, mid, txt: s.proposals.append((lead, cid, mid, txt)) or 0)
    # Selection branch (turn-arbitration): SENT-set presence + the select invoke.
    monkeypatch.setattr(actions_mod, "find_selectable_proposal_set", lambda lid: selectable_set)
    monkeypatch.setattr(actions_mod, "invoke_select_catering_proposal",
                        lambda lid, cid, mid, txt: s.selects.append((lid, cid, mid, txt)) or select_rc)
    monkeypatch.setattr(actions_mod, "send_canonical_followup_reply",
                        lambda cid, lid, message_id="": s.canonical.append((cid, lid)) or True)
    monkeypatch.setattr(hooks_mod, "_send_fresh_inquiry_clarification",
                        lambda cid, lid: s.clarify.append((cid, lid)) or True)
    monkeypatch.setattr(hooks_mod.catering_amendments, "capture_branch_b_amendment",
                        lambda **kw: s.captures.append(kw) or CaptureResult(
                            ok=capture_ok, amendment_id="A0001", idempotent=False))
    return s


def _reasons(s):
    return [a["reason"] for a in s.audits]


# ── Incident replay: new lead over stale + DETERMINISTIC generation ─────────
def test_incident_replay_opens_new_lead_and_generates_deterministically(monkeypatch):
    hooks_mod, actions_mod = _load_plugin()
    s = _wire(monkeypatch, hooks_mod, actions_mod, active_lead=_stale_lead())
    out = hooks_mod._try_f7_primary_intercept(INCIDENT, CHAT, _event(), allow_new_lead=True)
    # PR-B2: proposals are GENERATED deterministically against the NEW lead (LLM
    # bypassed ⇒ skip), NOT escaped to Hermes.
    assert out is not None and out["action"] == "skip"
    assert len(s.creates) == 1, "exactly one new lead opened over the stale one"
    # Turn-arbitration 2026-07-26: ONE bounded response. The create SUPPRESSES its F14
    # sample menu (a proposal ask follows), NO cross-reference "is this separate?"
    # question is sent (the contradiction already makes the event distinct), and the
    # generated tiered set is the single customer send.
    assert s.creates[0]["suppress_customer_ack"] is True, "F14 suppressed; tiered set is the one send"
    # A SENT set is created for the NEW lead (L0099 from the create spy), deterministically.
    assert len(s.proposals) == 1 and s.proposals[0][0] == "L0099", \
        "proposals generated against the new lead via --auto-generate-from-menu"
    assert _reasons(s) == [
        "f7_fresh_inquiry_new_lead_over_stale",
        "f7_proposal_request_deterministic_generation",
    ]
    assert "f7_proposal_request_escaped_to_dispatcher" not in _reasons(s)
    assert "f7_primary_followup_suppressed" not in _reasons(s)
    assert s.captures == [], "the fresh inquiry must NOT be captured as a follow-up"
    assert s.canonical == [], "the 'with the owner' canonical reply must NOT fire"


# ── Plain proposal request → deterministic generation, no new lead ──────────
def test_proposal_request_only_generates_no_new_lead(monkeypatch):
    hooks_mod, actions_mod = _load_plugin()
    s = _wire(monkeypatch, hooks_mod, actions_mod, active_lead=_stale_lead())
    out = hooks_mod._try_f7_primary_intercept(
        "Can you send me two sample menus?", CHAT, _event("wamid.PR"), allow_new_lead=True)
    # PR-B2: plain proposal request GENERATES against the existing active lead.
    assert out is not None and out["action"] == "skip"
    assert s.creates == [], "a plain proposal request must NOT open a new lead"
    assert s.selects == [], "a plain proposal request is not a selection"
    assert len(s.proposals) == 1 and s.proposals[0][0] == "L0017", \
        "generated deterministically against the existing active lead"
    assert _reasons(s) == ["f7_proposal_request_deterministic_generation"]
    assert s.captures == [] and s.canonical == []


# ── Mix-and-match recompose → still escapes to Hermes, NOT auto-generation ──
def test_mix_and_match_request_escapes_to_hermes_recompose(monkeypatch):
    hooks_mod, actions_mod = _load_plugin()
    s = _wire(monkeypatch, hooks_mod, actions_mod, active_lead=_stale_lead())
    # A proposal-request phrasing (reaches the escape branch) that ALSO names
    # option-section refs ⇒ a recompose, not plain generation.
    mix = "Can you send me a menu with option 1 starters and the option 2 mains?"
    assert actions_mod.is_proposal_request_escape(mix) and actions_mod.is_mix_and_match_request(mix)
    out = hooks_mod._try_f7_primary_intercept(mix, CHAT, _event("wamid.MIX"), allow_new_lead=True)
    # Recompose stays a Hermes-routed script path (--recompose-from-sent); cf-router
    # takes back only PLAIN generation, never the mix-and-match merge.
    assert out is None
    assert s.proposals == [], "mix-and-match must NOT run --auto-generate-from-menu"
    assert s.creates == [], "mix-and-match must NOT open a new lead"
    assert _reasons(s) == ["f7_proposal_request_escaped_to_dispatcher"]
    assert s.captures == [] and s.canonical == []


# ── R2A canary amendment → unchanged durable-capture path ───────────────────
def test_r2a_canary_amendment_keeps_capture_path(monkeypatch):
    hooks_mod, actions_mod = _load_plugin()
    s = _wire(monkeypatch, hooks_mod, actions_mod, active_lead=_stale_lead())
    out = hooks_mod._try_f7_primary_intercept(
        "Please update the headcount for my catering request from 45 to 60 guests",
        CHAT, _event("wamid.AMEND"), allow_new_lead=True)
    assert out is not None and out["action"] == "skip"
    assert "follow-up" in out["reason"]
    assert len(s.captures) == 1, "amendment-phrased text is durably captured (R2A)"
    assert s.creates == [], "an amendment must NEVER open a second lead"
    assert _reasons(s) == ["f7_primary_followup_suppressed"]
    assert len(s.canonical) == 1


# ── Inquiry-shaped, matching identity → one clarification, no lead/capture ──
def test_inquiry_matching_identity_clarifies_once(monkeypatch):
    hooks_mod, actions_mod = _load_plugin()
    s = _wire(monkeypatch, hooks_mod, actions_mod,
              active_lead=_stale_lead(event_date="2026-08-08", headcount=120))
    out = hooks_mod._try_f7_primary_intercept(
        "We're finalizing catering for 120 guests for the wedding on August 8th.",
        CHAT, _event("wamid.SAME"), allow_new_lead=True)
    assert out is not None and out["action"] == "skip" and "clarified" in out["reason"]
    assert len(s.clarify) == 1, "exactly one clarification"
    assert s.creates == [] and s.captures == [], "no lead created, no capture"
    assert _reasons(s) == ["f7_fresh_inquiry_ambiguous_clarification"]


# ── Contradiction on date only / headcount only → a new lead each ───────────
def test_contradiction_date_only_opens_new_lead(monkeypatch):
    hooks_mod, actions_mod = _load_plugin()
    s = _wire(monkeypatch, hooks_mod, actions_mod,
              active_lead=_stale_lead(event_date="2026-07-04", headcount=120))
    out = hooks_mod._try_f7_primary_intercept(
        "Catering for 120 guests for the wedding on August 8th please.",
        CHAT, _event("wamid.DATE"), allow_new_lead=True)
    assert out is not None and out["action"] == "skip" and "fresh inquiry" in out["reason"]
    # Distinct event with NO proposal ask → new lead, F14 kept as the one response,
    # NO cross-reference question (turn-arbitration 2026-07-26).
    assert len(s.creates) == 1
    assert s.creates[0]["suppress_customer_ack"] is False, "no proposal ask → F14 is the one send"
    assert s.proposals == [], "no proposal ask → no tiered generation"
    assert _reasons(s) == ["f7_fresh_inquiry_new_lead_over_stale"]


def test_contradiction_headcount_only_opens_new_lead(monkeypatch):
    hooks_mod, actions_mod = _load_plugin()
    s = _wire(monkeypatch, hooks_mod, actions_mod,
              active_lead=_stale_lead(event_date=None, headcount=60))
    out = hooks_mod._try_f7_primary_intercept(
        "Need catering for 200 guests at the reception.",
        CHAT, _event("wamid.HC"), allow_new_lead=True)
    assert out is not None and out["action"] == "skip" and "fresh inquiry" in out["reason"]
    assert len(s.creates) == 1
    assert _reasons(s) == ["f7_fresh_inquiry_new_lead_over_stale"]


# ── Idempotency: same message id twice → one lead ───────────────────────────
def test_idempotency_same_message_twice_one_lead(monkeypatch):
    hooks_mod, actions_mod = _load_plugin()
    seen: dict = {}

    def _dedup_create(kw):
        mid = kw["message_id"]
        if mid in seen:
            return (True, seen[mid])
        detail = '{"lead_id":"L0%03d"}' % (99 + len(seen))
        seen[mid] = detail
        return (True, detail)

    s = _wire(monkeypatch, hooks_mod, actions_mod,
              active_lead=_stale_lead(event_date="2026-07-04", headcount=60),
              create_returns=_dedup_create)
    ev = _event("wamid.DUP")
    hooks_mod._try_f7_primary_intercept(
        "Catering for 200 guests for the wedding on August 8th.", CHAT, ev, allow_new_lead=True)
    hooks_mod._try_f7_primary_intercept(
        "Catering for 200 guests for the wedding on August 8th.", CHAT, ev, allow_new_lead=True)
    # create-catering-lead dedups on (customer_phone, message_id): two calls, one unique lead.
    assert len(s.creates) == 2, "both inbounds reach the create path"
    assert len(seen) == 1, "the same message id yields exactly ONE lead (idempotent)"


# ── Amendment-phrased proposal request → amendment precedence (R2A) ─────────
def test_amendment_phrased_proposal_request_stays_r2a(monkeypatch):
    hooks_mod, actions_mod = _load_plugin()
    s = _wire(monkeypatch, hooks_mod, actions_mod, active_lead=_stale_lead())
    out = hooks_mod._try_f7_primary_intercept(
        "Actually, please change the sample menus you send.", CHAT, _event("wamid.AMPR"),
        allow_new_lead=True)
    assert out is not None and out["action"] == "skip" and "follow-up" in out["reason"]
    assert len(s.captures) == 1
    assert s.creates == []
    assert _reasons(s) == ["f7_primary_followup_suppressed"]


# ── Flag-off rollback → discriminator/escape dormant, R2A capture unchanged ─
def test_flag_off_falls_back_to_r2a_capture(monkeypatch):
    hooks_mod, actions_mod = _load_plugin()
    s = _wire(monkeypatch, hooks_mod, actions_mod, active_lead=_stale_lead())
    hooks_mod.F7_PROPOSAL_BRANCH_ENABLED = False
    out = hooks_mod._try_f7_primary_intercept(INCIDENT, CHAT, _event("wamid.OFF"), allow_new_lead=True)
    # PR-A block skipped → pre-PR-A behavior: durable capture + canonical reply.
    assert out is not None and out["action"] == "skip" and "follow-up" in out["reason"]
    assert len(s.captures) == 1 and s.creates == []
    assert _reasons(s) == ["f7_primary_followup_suppressed"]


# ── Turn-arbitration: outbound-count proxy ──────────────────────────────────
def _customer_sends(s) -> int:
    """Count customer-facing outbounds a turn produced (unit-level proxy). A create
    sends its F14 sample menu IFF suppress_customer_ack is False; the cross-reference
    send is gone; every other channel is one send each."""
    f14 = sum(1 for c in s.creates if not c.get("suppress_customer_ack"))
    return f14 + len(s.proposals) + len(s.clarify) + len(s.canonical) + len(s.selects)


def _sent_set(lead_id="L0017"):
    return {"proposal_set_id": f"CPS-{lead_id}-000001", "lead_id": lead_id,
            "status": "SENT", "outbound_message_id": "mid_sent"}


# ── Compound intent: "I like Option 2 + pricing" is a SELECTION, not regen ──
def test_compound_selection_plus_pricing_records_once_no_regeneration(monkeypatch):
    hooks_mod, actions_mod = _load_plugin()
    s = _wire(monkeypatch, hooks_mod, actions_mod, active_lead=_stale_lead(),
              selectable_set=_sent_set("L0017"))
    out = hooks_mod._try_f7_primary_intercept(
        "I like Option 2. Can you send me quote and prices.", CHAT, _event("wamid.SEL2"),
        allow_new_lead=True)
    assert out is not None and out["action"] == "skip" and "selection" in out["reason"]
    assert len(s.selects) == 1 and s.selects[0][0] == "L0017", "recorded the selection ONCE"
    assert s.proposals == [], "must NOT regenerate or re-send the menus"
    assert s.creates == [], "must NOT open a new lead"
    assert s.captures == [], "a compound selection is NOT an amendment capture"
    assert _reasons(s) == ["f7_proposal_selection"]
    assert _customer_sends(s) == 1, "one bounded response (the selection ack)"


# ── Redundant bare "Option 2" after the selection is idempotent (no double-select) ──
def test_redundant_option_after_selection_is_idempotent(monkeypatch):
    hooks_mod, actions_mod = _load_plugin()
    # Once the selection was recorded the set is SELECTED (no longer SENT), so
    # find_selectable_proposal_set returns None and the redundant "Option 2" cannot
    # re-enter the selection branch — no second select fires.
    s = _wire(monkeypatch, hooks_mod, actions_mod, active_lead=_stale_lead(), selectable_set=None)
    hooks_mod._try_f7_primary_intercept("Option 2", CHAT, _event("wamid.SEL3"), allow_new_lead=True)
    assert s.selects == [], "no second selection fires (no SENT set remains)"
    assert s.proposals == [], "and no regeneration"
    assert s.creates == [], "and no new lead"


# ── Amendment-phrased tier change stays R2A even when it names a tier ────────
def test_amendment_named_tier_stays_capture_not_selection(monkeypatch):
    hooks_mod, actions_mod = _load_plugin()
    s = _wire(monkeypatch, hooks_mod, actions_mod, active_lead=_stale_lead(),
              selectable_set=_sent_set("L0017"))
    out = hooks_mod._try_f7_primary_intercept(
        "Actually make it premium instead.", CHAT, _event("wamid.AMT"), allow_new_lead=True)
    assert out is not None and "follow-up" in out["reason"]
    assert s.selects == [], "amendment-phrased tier change must NOT be read as a selection"
    assert len(s.captures) == 1, "it keeps the R2A durable-capture path"
    assert _reasons(s) == ["f7_primary_followup_suppressed"]


# ── Full 3-message live-transcript reproduction (2026-07-26 smoke) ───────────
def test_live_transcript_three_messages_one_response_each(monkeypatch):
    """The exact 2026-07-26 smoke: (1) wedding/180 fresh inquiry over an open stale
    lead → ONE bounded response (new lead, F14 suppressed, tiered set, NO 'is this
    separate?' question); (2) compound select+pricing → records Option 2 once, advances,
    no menu re-send; (3) redundant 'Option 2' → idempotent (no double-select)."""
    hooks_mod, actions_mod = _load_plugin()

    # Message 1 — fresh wedding inquiry (distinct: 180 vs stale 60) that also asks for menus.
    s1 = _wire(monkeypatch, hooks_mod, actions_mod,
               active_lead=_stale_lead(lead_id="L0019", event_date="2026-07-04", headcount=60),
               selectable_set=None)
    msg1 = ("Hello I have a wedding coming up for 180 guests. Please send me two sample "
            "menus so I can decide.")
    out1 = hooks_mod._try_f7_primary_intercept(msg1, CHAT, _event("wamid.M1"), allow_new_lead=True)
    assert out1 is not None and out1["action"] == "skip"
    assert len(s1.creates) == 1 and s1.creates[0]["suppress_customer_ack"] is True
    assert len(s1.proposals) == 1, "tiered options generated as the single response"
    assert _reasons(s1) == [
        "f7_fresh_inquiry_new_lead_over_stale",
        "f7_proposal_request_deterministic_generation",
    ], "no independent ack + dup-warning + proposal — one composed outcome"
    assert s1.clarify == [] and s1.canonical == [] and s1.captures == []
    assert _customer_sends(s1) == 1, "message 1 → exactly ONE customer outbound"

    # Message 2 — compound selection + pricing against the now-active lead's SENT set.
    s2 = _wire(monkeypatch, hooks_mod, actions_mod,
               active_lead=_stale_lead(lead_id="L0020", event_date="2026-07-04", headcount=180),
               selectable_set=_sent_set("L0020"))
    out2 = hooks_mod._try_f7_primary_intercept(
        "I like Option 2. Can you send me quote and prices.", CHAT, _event("wamid.M2"),
        allow_new_lead=True)
    assert out2 is not None and "selection" in out2["reason"]
    assert len(s2.selects) == 1 and s2.selects[0][0] == "L0020", "Option 2 recorded once"
    assert s2.proposals == [], "menus NOT re-sent"
    assert _customer_sends(s2) == 1, "message 2 → exactly ONE customer outbound"

    # Message 3 — redundant "Option 2" after the set is consumed → no double-select.
    s3 = _wire(monkeypatch, hooks_mod, actions_mod,
               active_lead=_stale_lead(lead_id="L0020", event_date="2026-07-04", headcount=180),
               selectable_set=None)
    hooks_mod._try_f7_primary_intercept("Option 2", CHAT, _event("wamid.M3"), allow_new_lead=True)
    assert s3.selects == [], "redundant selection is idempotent — no double-select"
    assert s3.proposals == [] and s3.creates == []


# ── Enum-literal declaration guard ──────────────────────────────────────────
def test_new_reason_literals_are_enum_members():
    from typing import get_args
    import schemas
    allowed = set(get_args(schemas.CfRouterIntercepted.model_fields["reason"].annotation))
    for reason in (
        "f7_proposal_request_deterministic_generation",
        "f7_proposal_request_escaped_to_dispatcher",
        "f7_fresh_inquiry_new_lead_over_stale",
        "f7_fresh_inquiry_ambiguous_clarification",
    ):
        assert reason in allowed, f"{reason} missing from CfRouterIntercepted.reason"
