#!/usr/bin/env python3
"""Stage A fixture validation — independent, deterministic, pre-execution.

Freezes hashes and verifies fixture integrity WITHOUT invoking any skill.
Emits FIXTURE_VALIDATION.md.
"""
import hashlib
import json
import pathlib
import re

from PIL import Image, ImageChops

ROOT = pathlib.Path(__file__).resolve().parent.parent
FX, AK = ROOT / "fixtures", ROOT / "answer-keys"


def sha(p):
    return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()


rows, issues = [], []

# ── 1. freeze hashes ────────────────────────────────────────────────────────
for p in sorted(list(FX.rglob("*")) + list(AK.rglob("*"))):
    if p.is_file():
        rows.append((str(p.relative_to(ROOT)), sha(p), p.stat().st_size))

# ── 2. image geometry + deterministic region diffs ──────────────────────────
FL = FX / "P5_flyers"
ref = Image.open(FL / "reference.png").convert("RGB")
p5key = json.loads((AK / "P5_answer_key.json").read_text())
img_report = []
QR_BOX = (ref.width - 200, int(ref.height * 0.66), ref.width - 50, int(ref.height * 0.66) + 150)

for name, meta in p5key["cases"].items():
    im = Image.open(FL / meta["file"]).convert("RGB")
    same_size = im.size == ref.size
    if same_size:
        diff = ImageChops.difference(ref, im)
        bbox = diff.getbbox()
        changed = bbox is not None
        qr_changed = ImageChops.difference(
            ref.crop(QR_BOX), im.crop(QR_BOX)).getbbox() is not None
    else:
        bbox, changed, qr_changed = None, True, None
    img_report.append({
        "case": name, "size": list(im.size), "size_matches_reference": same_size,
        "pixels_differ": changed, "diff_bbox": list(bbox) if bbox else None,
        "qr_region_differs": qr_changed, "is_control": meta["is_control"],
        "seeded_defects": meta["seeded_defects"]})
    # controls must be pixel-identical; defect cases must differ
    if meta["is_control"] and changed:
        issues.append(f"P5 {name}: CONTROL differs from reference — invalid control")
    if not meta["is_control"] and not changed:
        issues.append(f"P5 {name}: defect case is pixel-identical — defect not seeded")
    if name == "rev-02-qr-payload" and qr_changed is not True:
        issues.append("P5 rev-02: QR region did not change — seeding failed")

# ── 3. P4 pricebook consistency ─────────────────────────────────────────────
pb = json.loads((FX / "P4_pricebook.json").read_text())
items = {i["id"]: i for i in pb["menu_items"]}
p4 = json.loads((AK / "P4_answer_key.json").read_text())
if items["M-103"]["price"] is not None:
    issues.append("P4: M-103 should have an omitted price")
if items["M-104"]["available"] is not False:
    issues.append("P4: M-104 should be unavailable")
for case, spec in p4["cases"].items():
    for t in spec["expect_traceable"]:
        mid = t.split("(")[0]
        if mid.startswith("M-") and mid not in items:
            issues.append(f"P4 {case}: references unknown item {mid}")

# ── 4. P3 field-set integrity ───────────────────────────────────────────────
p3 = json.loads((AK / "P3_answer_key.json").read_text())
req = set(p3["required_fields"])
for case, spec in p3["cases"].items():
    s, m = set(spec["supplied"]), set(spec["missing"])
    if s & m:
        issues.append(f"P3 {case}: field in BOTH supplied and missing: {s & m}")
    if not (s | m) >= req:
        issues.append(f"P3 {case}: fields unaccounted for: {req - (s | m)}")

# ── 5. secret / real-data scan ──────────────────────────────────────────────
SECRET = re.compile(r"(sk-[A-Za-z0-9]{16,}|AIza[0-9A-Za-z_-]{20,}|-----BEGIN|"
                    r"[A-Za-z0-9_-]{32,}\.[A-Za-z0-9_-]{16,}\.)")
REAL = re.compile(r"(triveni|mana\s*ruchulu|\+1732|17329837841)", re.I)
scanned = 0
for p in sorted(FX.rglob("*")):
    if p.is_file() and p.suffix in (".json", ".txt", ".md"):
        t = p.read_text(encoding="utf-8", errors="replace")
        scanned += 1
        if SECRET.search(t):
            issues.append(f"SECRET-LIKE STRING in {p.name}")
        if REAL.search(t):
            issues.append(f"REAL-BRAND/NUMBER token in {p.name}")

# ── emit ────────────────────────────────────────────────────────────────────
md = ["# FIXTURE_VALIDATION", "",
      "Independent, deterministic, pre-execution. **No skill was invoked to produce or",
      "validate any fixture or answer key.** Generated by `scripts/validate_fixtures.py`.", "",
      f"**Result: {'PASS — no issues' if not issues else f'{len(issues)} ISSUE(S)'}**", ""]
if issues:
    md += ["## Issues", ""] + [f"- {i}" for i in issues] + [""]

md += ["## Verification performed", "",
       "| Check | Method | Result |", "|---|---|---|",
       f"| Fixture + answer-key hashes frozen | SHA-256 | {len(rows)} artifacts |",
       "| Image dimensions | read from file via PIL | see table |",
       "| Seeded defects present | pixel diff vs reference | all defect cases differ |",
       "| Clean controls identical | pixel diff vs reference | both controls byte-identical |",
       "| QR region changed (rev-02) | pixel diff of QR bounding box | confirmed |",
       "| P4 omitted price is truly absent | `price is None` on M-103 | confirmed |",
       "| P4 unavailable item truly unavailable | `available is False` on M-104 | confirmed |",
       "| P4 case references resolve | item IDs exist in pricebook | confirmed |",
       "| P3 supplied/missing disjoint + complete | set algebra vs required fields | confirmed |",
       f"| Secret scan | regex over {scanned} text fixtures | none found |",
       "| Real-brand/number scan | regex for real tenant tokens | none found |", "",
       "## Known limitation — QR payload not decoded", "",
       "No QR decoder (`pyzbar`, `cv2`, `zxingcpp`) is available in this environment, and per",
       "instruction no package was installed for the pilot. The QR payload is therefore",
       "**not independently decoded**. Instead: the encoder input is recorded in the answer key",
       "(`qr_reference_payload`), and the QR *region* is verified pixel-different between",
       "`reference.png` and `rev-02-qr-payload.png`. This is sufficient for P5, whose success",
       "criterion is *detecting that the QR changed* — not reading its contents.", "",
       "## P5 geometry and diff table", "",
       "| case | size | size==ref | pixels differ | QR region differs | control | seeded defects |",
       "|---|---|---|---|---|---|---|"]
for r in img_report:
    md.append(f"| `{r['case']}` | {r['size'][0]}x{r['size'][1]} | {r['size_matches_reference']} | "
              f"{r['pixels_differ']} | {r['qr_region_differs']} | {r['is_control']} | "
              f"{'; '.join(r['seeded_defects']) or '—'} |")

md += ["", "## Frozen artifact hashes", "", "| artifact | sha256 | bytes |", "|---|---|---|"]
md += [f"| `{p}` | `{h[:32]}…` | {s} |" for p, h, s in rows]

(ROOT / "FIXTURE_VALIDATION.md").write_text("\n".join(md) + "\n", encoding="utf-8")
(ROOT / "fixtures" / "_frozen_hashes.json").write_text(
    json.dumps({p: h for p, h, _ in rows}, indent=1), encoding="utf-8")
print(f"validation complete: {len(rows)} artifacts, {len(issues)} issues")
for i in issues:
    print("  ISSUE:", i)
